demockrazy/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="vote/", permanent=False)),
    url(r'^vote/', include('vote.urls', namespace='vote')),
    url(r'^admin/', admin.site.urls),
]

vote/urls.py
from django.conf.urls import include, patterns, url

from . import views

pollpatterns = [
    url(r'^$', views.poll, name='poll'),
    url(r'^vote$', views.vote, name='vote'),
    url(r'^success$', views.success, name='success'),
    url(r'^manage$', views.manage, name='manage'),
    url(r'^results$', views.results, name='result'),
]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^(?P<poll_identifier>[a-zA-Z0-9]+)/', include(pollpatterns)),
]

vote/models.py
from django.db import models
from django.utils.timezone import now

import random
import string


POLL_TYPES = ['simple_choice', 'multiple_choice']


def rand_string(length):
    return ''.join(random.SystemRandom().choice(
        string.ascii_letters + string.digits
    ) for _ in range(length))


def mk_admin_token():
    return rand_string(256)


def mk_identifier():
    id = rand_string(64)
    if not Poll.objects.filter(identifier=id).exists():
        return id
    else:
        return mk_identifier()


def mk_token():
    tok = rand_string(128)
    if not Token.objects.filter(token_string=tok).exists():
        return tok
    else:
        return mk_token()


class Poll(models.Model):
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=20, default="simple_choice")
    num_tokens = models.IntegerField(blank=True, null=True)
    question_text = models.TextField()
    pub_date = models.DateTimeField('date published', default=now, blank=True)
    creator_token = models.CharField(max_length=512, default=mk_admin_token)
    identifier = models.CharField(max_length=64, default=mk_identifier)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_amount_used_unused(self):
        choices = Choice.objects.filter(poll=self)
        amount_remaining_tokens = len(Token.objects.filter(poll=self))
        if self.num_tokens is not None:
            total = self.num_tokens
            amount_redeemed_tokens = total - amount_remaining_tokens
        else:
            amount_redeemed_tokens = 0
            for choice in choices:
                amount_redeemed_tokens += choice.votes
            total = amount_redeemed_tokens + amount_remaining_tokens
        return (amount_redeemed_tokens, amount_remaining_tokens, total)


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.TextField()
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "%s - %s" % (self.poll, self.choice_text)


class Token(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    token_string = models.CharField(default=mk_token, max_length=128)

    def __str__(self):
        return "%s Token" % self.poll

vote/views.py
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.db.models import F
from django.shortcuts import render, get_object_or_404
from smtplib import SMTPException

from .models import POLL_TYPES, Poll, Choice, Token


def poll(request, poll_identifier):
    poll = get_object_or_404(Poll, identifier=poll_identifier)
    token = request.GET.get('token', '')
    error_message = None
    if token:
        try:
            token_object = Token.objects.get(token_string=token)
        except Token.DoesNotExist:
            error_message = "This token is invalid. Maybe you voted already?"
    amount_redeemed_tokens, amount_remaining_tokens, amount_tokens_total = poll.get_amount_used_unused()
    if poll.is_active:
        return render(request, 'vote/poll.html', {
            'poll': poll,
            'token': token,
            'amount_redeemed_tokens': amount_redeemed_tokens,
            'amount_remaining_tokens': amount_remaining_tokens,
            'amount_tokens_total': amount_tokens_total,
            'error_message': error_message,
        })
    else:
        return HttpResponseRedirect(reverse('vote:result', args=(poll_identifier,)))


def index(request):
    return render(request, 'vote/index.html')


def create(request):
    def parse_mails(mails):
        result = []
        for mail in mails.split("\n"):
            mail = mail.strip()
            if not mail:
                continue
            if mail.count("@") != 1 or mail.split("@")[1].count(".") == 0:
                raise ValidationError("Mail %s invalid" % mail)
            result.append(mail)
        return result

    def parse_choices(choices):
        result = []
        for choice in choices.split("\n"):
            choice = choice.strip()
            if not choice:
                continue
            result.append(choice)
        return result

    def create_choice_objects(choices, poll):
        result = []
        for choice in choices:
            choice_obj = Choice(poll=poll, choice_text=choice)
            choice_obj.save()
            result.append(choice_obj)
        return result

    def create_token_objects(poll, amount):
        result = []
        for i in range(amount):
            token = Token(poll=poll)
            token.save()
            result.append(token)
        return result

    def send_mail_or_print(args, print_only=False):
        if print_only:
            print(*args)
        else:
            send_mail(*args, fail_silently=False)

    def send_creator_mail(poll, creator_mail, creator_token, print_only=False):
        manage_url = settings.VOTE_BASE_URL + reverse('vote:manage', args=(poll.identifier,))
        args = (settings.VOTE_ADMIN_MAIL_SUBJECT % {"title": poll.title},
                settings.VOTE_ADMIN_MAIL_TEXT % {
                    "title": poll.title, "manage_url": manage_url, "creator_token": creator_token
                },
                settings.VOTE_MAIL_FROM,
                [creator_mail],
                )
        send_mail_or_print(args, print_only)

    def send_mails_with_tokens(poll, voter_mails, tokens, print_only=False):
        token_strings = [token.token_string for token in tokens]
        errors = []
        for voter_mail in voter_mails:
            poll_url_with_token = settings.VOTE_BASE_URL + reverse('vote:poll', args=(
                poll.identifier,)) + '?token=' + token_strings.pop()
            args = (settings.VOTE_MAIL_SUBJECT % {"title": poll.title},
                    settings.VOTE_MAIL_TEXT % {
                        "title": poll.title,
                        "poll_url_with_token": poll_url_with_token,
                        "vote_base_url": settings.VOTE_BASE_URL
                    },
                    settings.VOTE_MAIL_FROM,
                    [voter_mail],
                    )
            try:
                send_mail_or_print(args, print_only)
            except SMTPException as e:
                errors.append(str(e))
            except UnicodeEncodeError as e:
                errors.append("%s " % voter_mail + str(e))
        return errors
    p_title = request.POST['title']
    p_type = request.POST['type']
    if p_type not in POLL_TYPES:
        raise Exception('Invalid poll type')
    p_description = request.POST['description']
    creator_mail = request.POST['creator_mail']
    voter_mails = request.POST['voter_mails']
    choices = request.POST['choices']
    voter_mails = parse_mails(voter_mails)
    choices = parse_choices(choices)
    poll = Poll(title=p_title, type=p_type, num_tokens=len(voter_mails), question_text=p_description)
    poll.save()
    choice_objects = create_choice_objects(choices, poll)
    tokens = create_token_objects(poll, len(voter_mails))
    send_creator_mail(poll, creator_mail, poll.creator_token, not settings.VOTE_SEND_MAILS)
    errors = send_mails_with_tokens(poll, voter_mails, tokens, not settings.VOTE_SEND_MAILS)
    context = {
            "errors": errors
        }
    return render(request, 'vote/create.html', context)


def vote(request, poll_identifier):
    def handle_vote_error(poll, request, message, token_string):
        amount_redeemed_tokens, amount_remaining_tokens, amount_tokens_total = poll.get_amount_used_unused()
        return render(request, 'vote/poll.html', {
            'poll': poll,
            'error_message': message,
            'token': token_string,
            "amount_redeemed_tokens": amount_redeemed_tokens,
            "amount_remaining_tokens": amount_remaining_tokens,
            "amount_tokens_total": amount_tokens_total
        })

    def close_poll_if_all_tokens_redeemed(poll):
        amount_redeemed_tokens, amount_remaining_tokens, amount_redeemed_tokens = poll.get_amount_used_unused()
        if amount_remaining_tokens == 0:
            poll.is_active = False
            poll.save()

    poll = get_object_or_404(Poll, identifier=poll_identifier)
    if not poll.is_active:
        return HttpResponseRedirect(reverse('vote:result', args=(poll_identifier,)))
    try:
        with transaction.atomic():
            token_string = request.POST['token']
            token = Token.objects.get(token_string=request.POST['token'])
            if token.poll == poll:
                if poll.type == 'multiple_choice':
                    for choice in Choice.objects.filter(poll=poll):
                        if request.POST['choice%i' % choice.id] == 'yes':
                            choice.votes = F('votes') + 1
                            choice.save()
                else:
                    selected_choice = poll.choice_set.get(pk=request.POST['choice'])
                    selected_choice.votes = F('votes') + 1
                    selected_choice.save()
                token.delete()
                close_poll_if_all_tokens_redeemed(poll)
                return HttpResponseRedirect(reverse('vote:success', args=(poll_identifier,)))
            else:
                return handle_vote_error(poll, request, "invalid token.", token_string)

    except KeyError:
        return handle_vote_error(poll, request, "Please fill out all fields.", token_string)
    except Choice.DoesNotExist:
        return handle_vote_error(poll, request, "You didn't select a choice.", token_string)
    except Token.DoesNotExist:
        return handle_vote_error(poll, request, "invalid token.", token_string)


def success(request, poll_identifier):
    poll = get_object_or_404(Poll, identifier=poll_identifier)
    return render(request, 'vote/success.html', {'poll': poll})


def manage(request, poll_identifier):
    poll = get_object_or_404(Poll, identifier=poll_identifier)
    error_message = None
    if not poll.is_active:
        return HttpResponseRedirect(reverse('vote:result', args=(poll_identifier,)))
    if request.method == 'POST':
        token = request.POST['token']
        if poll.creator_token == token:
            poll.is_active = False
            poll.save()
            return HttpResponseRedirect(reverse('vote:result', args=(poll_identifier,)))
        error_message = 'Wrong management token'
    amount_redeemed_tokens, amount_remaining_tokens, amount_tokens_total = poll.get_amount_used_unused()
    context = {
        'poll': poll,
        'amount_redeemed_tokens': amount_redeemed_tokens,
        'amount_remaining_tokens': amount_remaining_tokens,
        'amount_tokens_total': amount_tokens_total,
        'error_message': error_message,
    }
    return render(request, 'vote/manage.html', context)


def results(request, poll_identifier):
    poll = get_object_or_404(Poll, identifier=poll_identifier)
    amount_redeemed_tokens, amount_remaining_tokens, amount_tokens_total = poll.get_amount_used_unused()
    if poll.is_active:
        return HttpResponseRedirect(reverse('vote:poll', args=(poll_identifier,)))
    return render(request, 'vote/results.html', {
        'poll': poll,
        'amount_redeemed_tokens': amount_redeemed_tokens,
        'amount_remaining_tokens': amount_remaining_tokens,
        'amount_tokens_total': amount_tokens_total,
    })

vote/templates/vote/create.html
{% extends 'base.html' %}

{% block content %}
<h1>poll created</h1>

{% if errors %}
  <b>Unfortunately, the following errors were encountered while dispatching mails.</b><br>
  {% for error in errors %}
    {{ error }}<br>
  {% endfor %}
{% endif %}
{% endblock %}

vote/templates/vote/index.html
{% extends 'base.html' %}

{% block content %}
<h1>create a new poll</h1>

{% if error_message %}<p>{{ error_message }}</p>{% endif %}

<form action="{% url 'vote:create' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="title">poll title:</label>
        <input class="form-control" type="text" name="title" id="title">
    </div>

    <div class="form-group">
        <label for="type">poll type:</label>
        <select name="type" id="type">
            <option value="simple_choice" selected>Simple Choice</option>
            <option value="multiple_choice">Multiple Choice</option>
        </select>
    </div>

    <div class="form-group">
        <label for="description">description:</label>
        <textarea class="form-control" name="description" id="description" rows="10"></textarea>
    </div>

    <div class="form-group">
    <label for="choices">choices (separated by line):</label>
    <textarea class="form-control" name="choices" id="choices" rows="18"></textarea>
    </div>

    <div class="form-group">
        <label for="creator_mail">admin mail:</label>
        <input class="form-control" type="email" name="creator_mail" id="creator_mail">
    </div>

    <div class="form-group">
        <label for="voter_mails">recipients (separated by line):</label>
        <textarea class="form-control" name="voter_mails" id="voter_mails" rows="23"></textarea>
    </div>

    <input class="btn btn-primary" type="submit" value="submit">
</form>
{% endblock %}

vote/templates/vote/manage.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ poll }}</h1>
{% if error_message %}
<div class="alert alert-danger" role="alert">{{ error_message }}</div>
{% endif %}
<form action="{% url 'vote:manage' poll_identifier=poll.identifier %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="token">Management Token</label>
        <input type="text" name="token" id="token" class="form-control">
    </div>
    <input type="submit" class="btn btn-primary" value="Deactivate">
</form>
{% include 'vote/token_state.html' %}
{% endblock %}

vote/templates/vote/poll.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ poll }}</h1>
<p>{{ poll.question_text }}</p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vote:vote' poll_identifier=poll.identifier %}" method="post">
    {% csrf_token %}
    {% if poll.type == 'simple_choice' %}
    {% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    {% else %}
    <table class="table">
        <tr>
            <th></th>
            <th>yes</th>
            <th>no</th>
        </tr>
        {% for choice in poll.choice_set.all %}
        <tr>
            <td><label>{{ choice.choice_text }}</label></td>
            <td><input type="radio" name="choice{{ choice.id }}" value="yes"/></td>
            <td><input type="radio" name="choice{{ choice.id }}" value="no"/></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <label for="token">Your voting token:</label> <input type="text" id="token" name="token" value="{{token}}">
    <input type="submit" value="Vote"/>
</form>
{% include 'vote/token_state.html' %}
{% endblock %}

vote/templates/vote/results.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<h1>results for poll {{ poll.title }}</h1>

<table class="table">
    <tr>
        <th>Choice</td>
        <th>Votes</td>
    </tr>
    {% for choice in poll.choice_set.all %}
        <tr>
            <td>{{ choice.choice_text }}</td>
            <td>{{ choice.votes }}</td>
        </tr>
    {% endfor %}
    <tr>
        <td>Abstentions</td>
        <td>{{ amount_remaining_tokens }}</td>
    </tr>
    <tr>
        <td>Total Voters</td>
        <td>{{ poll.num_tokens }}</td>
    </tr>
</table>

<div id="results-chart"></div>
{% endblock %}

{% block js %}
<script>
$(function () {
    $('#results-chart').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: null
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            name: 'Votes',
            colorByPoint: true,
            data: [
                {% for choice in poll.choice_set.all %}
                    {
                        name: '{{ choice.choice_text }}',
                        y: {{ choice.votes }}
                    },
                {% endfor %}
                {% if poll.type == 'simple_choice' %}{
                    name: 'Abstentions',
                    y: {{ amount_remaining_tokens }}
                },{% endif %}
            ]
        }]
    });
});
</script>
{% endblock %}

vote/templates/vote/success.html
{% extends 'base.html' %}

{% block content %}
<h1>Vote on {{ poll.title }} successful</h1>
{% endblock %}

vote/templates/vote/token_state.html
<label></label>
<ul class="nav nav-pills" role="tablist">
    <li role="presentation"><b>Token State: </b></li>
    <li role="presentation">Total <span class="badge">{{ amount_tokens_total }}</span></li>
    <li role="presentation">Redeemed <span class="badge">{{ amount_redeemed_tokens }}</span></li>
    <li role="presentation">Remaining <span class="badge">{{ amount_remaining_tokens }}</span></li>
</ul>